[2025-05-02 23:42:31,410:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-02 23:42:31,421:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-02 23:45:12,531:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-02 23:45:12,533:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-02 23:56:04,365:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-02 23:56:04,368:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-02 23:56:45,109:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-02 23:56:45,112:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-02 23:58:04,723:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-02 23:58:04,725:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-02 23:58:10,869:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-02 23:58:10,871:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-03 00:00:06,728:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-03 00:00:06,730:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-03 00:00:56,027:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-03 00:00:56,038:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-03 00:00:56,040:INFO:5(module)s:created directory at: artifacts]
[2025-05-03 00:00:56,042:INFO:5(module)s:created directory at: artifacts/data_ingestion]
[2025-05-03 00:02:41,333:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-03 00:02:41,336:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-03 00:02:41,338:INFO:5(module)s:created directory at: artifacts]
[2025-05-03 00:02:41,340:INFO:5(module)s:created directory at: artifacts/data_ingestion]
[2025-05-03 00:02:43,567:INFO:5(module)s:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: C374:092A:131CEC:2B4F16:68150FCA
Accept-Ranges: bytes
Date: Fri, 02 May 2025 18:32:43 GMT
Via: 1.1 varnish
X-Served-By: cache-bom4747-BOM
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1746210762.464558,VS0,VE1092
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: eca38de1bc79563968077b993a94e273e6407242
Expires: Fri, 02 May 2025 18:37:43 GMT
Source-Age: 1

]
[2025-05-04 21:15:09,787:INFO:5(module)s:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-04 21:15:09,788:ERROR:5(module)s:'DataIngestionTrainingPipeline' object has no attribute 'main']
Traceback (most recent call last):
  File "C:\Users\MONISH\OneDrive\Documents\Data_science 2024\CNN_classifier\CNN_Classifier\main.py", line 8, in <module>
    obj.main()
    ^^^^^^^^
AttributeError: 'DataIngestionTrainingPipeline' object has no attribute 'main'
[2025-05-04 21:15:39,701:INFO:5(module)s:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-04 21:15:39,702:ERROR:5(module)s:'DataIngestionTrainingPipeline' object has no attribute 'main']
Traceback (most recent call last):
  File "C:\Users\MONISH\OneDrive\Documents\Data_science 2024\CNN_classifier\CNN_Classifier\main.py", line 8, in <module>
    obj.main()
    ^^^^^^^^
AttributeError: 'DataIngestionTrainingPipeline' object has no attribute 'main'
[2025-05-04 21:41:47,069:INFO:5(module)s:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-04 21:41:47,070:ERROR:5(module)s:'DataIngestionTrainingPipeline' object has no attribute 'main']
Traceback (most recent call last):
  File "C:\Users\MONISH\OneDrive\Documents\Data_science 2024\CNN_classifier\CNN_Classifier\main.py", line 8, in <module>
    obj.main()
    ^^^^^^^^
AttributeError: 'DataIngestionTrainingPipeline' object has no attribute 'main'
[2025-05-04 21:45:00,567:INFO:5(module)s:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-04 21:45:00,579:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-04 21:45:00,591:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-04 21:45:00,592:INFO:5(module)s:created directory at: artifacts]
[2025-05-04 21:45:00,593:INFO:5(module)s:created directory at: artifacts/data_ingestion]
[2025-05-04 21:45:02,694:INFO:5(module)s:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: F606:08E7:F3191:2FDB4B:68179282
Accept-Ranges: bytes
Date: Sun, 04 May 2025 16:15:02 GMT
Via: 1.1 varnish
X-Served-By: cache-bom4733-BOM
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1746375301.231853,VS0,VE905
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: f498847570d42fc34d09c358c731b37fb0a9b647
Expires: Sun, 04 May 2025 16:20:02 GMT
Source-Age: 1

]
[2025-05-04 21:45:03,173:INFO:5(module)s:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-05-04 23:11:20,916:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-04 23:11:20,919:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-04 23:11:20,921:INFO:5(module)s:created directory at: artifacts]
[2025-05-04 23:11:41,720:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-04 23:11:41,723:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-04 23:11:41,724:INFO:5(module)s:created directory at: artifacts]
[2025-05-04 23:12:38,621:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-04 23:12:38,624:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-04 23:12:38,625:INFO:5(module)s:created directory at: artifacts]
[2025-05-04 23:13:39,029:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-04 23:13:39,032:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-04 23:13:39,033:INFO:5(module)s:created directory at: artifacts]
[2025-05-04 23:15:18,609:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-04 23:15:18,612:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-04 23:15:18,614:INFO:5(module)s:created directory at: artifacts]
[2025-05-04 23:15:18,615:INFO:5(module)s:created directory at: artifacts/prepare_base_model]
[2025-05-04 23:15:19,163:WARNING:5(module)s:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-04 23:15:19,386:WARNING:5(module)s:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-04 23:19:09,570:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-04 23:19:09,574:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-04 23:19:09,576:INFO:5(module)s:created directory at: artifacts]
[2025-05-04 23:19:09,578:INFO:5(module)s:created directory at: artifacts/prepare_base_model]
[2025-05-04 23:19:10,012:WARNING:5(module)s:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-04 23:19:10,216:WARNING:5(module)s:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-05 01:00:36,781:INFO:5(module)s:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-05 01:00:36,783:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-05 01:00:36,785:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-05 01:00:36,786:INFO:5(module)s:created directory at: artifacts]
[2025-05-05 01:00:36,788:INFO:5(module)s:created directory at: artifacts/data_ingestion]
[2025-05-05 01:00:39,048:INFO:5(module)s:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 6457:2340ED:3B4191:A860AD:6817C05D
Accept-Ranges: bytes
Date: Sun, 04 May 2025 19:30:38 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10239-MAA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1746387038.788481,VS0,VE880
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 896595d64c24821e2fe2dec86514c77710ede3da
Expires: Sun, 04 May 2025 19:35:38 GMT
Source-Age: 1

]
[2025-05-05 01:00:39,554:INFO:5(module)s:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-05-05 01:00:39,554:INFO:5(module)s:*******************]
[2025-05-05 01:00:39,554:INFO:5(module)s:>>>>>> stage Prepare base model started <<<<<<]
[2025-05-05 01:00:39,556:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-05 01:00:39,557:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-05 01:00:39,558:INFO:5(module)s:created directory at: artifacts]
[2025-05-05 01:00:39,559:INFO:5(module)s:created directory at: artifacts/prepare_base_model]
[2025-05-05 01:00:40,030:WARNING:5(module)s:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-05 01:00:40,242:WARNING:5(module)s:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-05 01:00:40,421:INFO:5(module)s:>>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-05-05 12:10:39,661:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-05 12:10:39,665:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-05 12:10:39,666:INFO:5(module)s:created directory at: artifacts]
[2025-05-05 12:10:39,669:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-05-05 12:10:39,672:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-05-05 15:58:32,963:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-05 15:58:32,976:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-05 15:58:32,978:INFO:5(module)s:created directory at: artifacts]
[2025-05-05 15:58:32,980:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-05-05 15:58:32,981:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-05-05 15:59:04,385:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-05 15:59:04,388:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-05 15:59:04,391:INFO:5(module)s:created directory at: artifacts]
[2025-05-05 15:59:04,392:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-05-05 15:59:04,394:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-05-05 23:33:46,361:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-05 23:33:46,382:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-05 23:33:46,389:INFO:5(module)s:created directory at: artifacts]
[2025-05-05 23:34:01,117:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-05 23:34:01,119:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-05 23:34:01,121:INFO:5(module)s:created directory at: artifacts]
[2025-05-05 23:34:20,876:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-05 23:34:20,878:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-05 23:34:20,880:INFO:5(module)s:created directory at: artifacts]
[2025-05-05 23:34:20,882:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-05-05 23:34:20,884:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-05-05 23:34:20,886:INFO:5(module)s:created directory at: artifacts\training]
[2025-05-05 23:34:21,322:WARNING:5(module)s:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-05 23:35:55,550:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-05 23:35:55,552:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-05 23:35:55,555:INFO:5(module)s:created directory at: artifacts]
[2025-05-05 23:35:55,557:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-05-05 23:35:55,558:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-05-05 23:35:55,558:INFO:5(module)s:created directory at: artifacts\training]
[2025-05-05 23:35:55,881:WARNING:5(module)s:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-05 23:36:59,869:WARNING:5(module)s:From C:\Users\MONISH\AppData\Local\Temp\ipykernel_32980\3925721481.py:5: The name tf.enable_eager_execution is deprecated. Please use tf.compat.v1.enable_eager_execution instead.
]
[2025-05-05 23:37:19,419:WARNING:5(module)s:From C:\Users\MONISH\AppData\Local\Temp\ipykernel_35312\3925721481.py:5: The name tf.enable_eager_execution is deprecated. Please use tf.compat.v1.enable_eager_execution instead.
]
[2025-05-05 23:37:19,468:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-05 23:37:19,478:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-05 23:37:19,479:INFO:5(module)s:created directory at: artifacts]
[2025-05-05 23:37:19,480:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-05-05 23:37:19,481:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-05-05 23:37:19,483:INFO:5(module)s:created directory at: artifacts\training]
[2025-05-05 23:37:19,746:WARNING:5(module)s:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-05 23:39:33,625:WARNING:5(module)s:From C:\Users\MONISH\AppData\Local\Temp\ipykernel_5180\3925721481.py:5: The name tf.enable_eager_execution is deprecated. Please use tf.compat.v1.enable_eager_execution instead.
]
[2025-05-05 23:39:33,679:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-05 23:39:33,681:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-05 23:39:33,682:INFO:5(module)s:created directory at: artifacts]
[2025-05-05 23:39:33,683:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-05-05 23:39:33,684:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-05-05 23:39:33,685:INFO:5(module)s:created directory at: artifacts\training]
[2025-05-05 23:39:34,080:WARNING:5(module)s:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-05 23:41:12,633:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-05 23:41:12,636:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-05 23:41:12,637:INFO:5(module)s:created directory at: artifacts]
[2025-05-05 23:41:12,638:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-05-05 23:41:12,640:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-05-05 23:41:12,641:INFO:5(module)s:created directory at: artifacts\training]
[2025-05-05 23:41:12,918:WARNING:5(module)s:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-05 23:43:02,734:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-05 23:43:02,737:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-05 23:43:02,739:INFO:5(module)s:created directory at: artifacts]
[2025-05-05 23:43:02,740:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-05-05 23:43:02,741:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-05-05 23:43:02,741:INFO:5(module)s:created directory at: artifacts\training]
[2025-05-05 23:43:03,040:WARNING:5(module)s:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-05 23:52:43,943:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-05 23:52:43,943:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-05 23:52:43,943:INFO:5(module)s:created directory at: artifacts]
[2025-05-05 23:52:43,943:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-05-05 23:52:43,943:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-05-05 23:52:43,943:INFO:5(module)s:created directory at: artifacts\training]
[2025-05-05 23:52:44,287:WARNING:5(module)s:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-06 00:18:38,535:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-06 00:18:38,535:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-06 00:18:38,535:INFO:5(module)s:created directory at: artifacts]
[2025-05-06 00:18:38,535:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-05-06 00:18:38,535:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-05-06 00:18:38,535:INFO:5(module)s:created directory at: artifacts\training]
[2025-05-06 00:26:46,191:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-06 00:26:46,196:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-06 00:26:46,198:INFO:5(module)s:created directory at: artifacts]
[2025-05-06 00:26:46,199:INFO:5(module)s:created directory at: artifacts/prepare_base_model]
[2025-05-06 00:27:04,193:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-06 00:27:04,195:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-06 00:27:04,197:INFO:5(module)s:created directory at: artifacts]
[2025-05-06 00:27:04,198:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-05-06 00:27:04,198:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-05-06 00:27:04,198:INFO:5(module)s:created directory at: artifacts\training]
[2025-05-06 01:28:58,996:INFO:5(module)s:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-06 01:28:58,999:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-06 01:28:59,002:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-06 01:28:59,003:INFO:5(module)s:created directory at: artifacts]
[2025-05-06 01:28:59,004:INFO:5(module)s:created directory at: artifacts/data_ingestion]
[2025-05-06 01:28:59,005:INFO:5(module)s:File already exists of size: ~ 11345 KB]
[2025-05-06 01:28:59,480:INFO:5(module)s:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-05-06 01:28:59,481:INFO:5(module)s:*******************]
[2025-05-06 01:28:59,481:INFO:5(module)s:>>>>>> stage Prepare base model started <<<<<<]
[2025-05-06 01:28:59,484:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-06 01:28:59,485:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-06 01:28:59,486:INFO:5(module)s:created directory at: artifacts]
[2025-05-06 01:28:59,489:INFO:5(module)s:created directory at: artifacts/prepare_base_model]
[2025-05-06 01:29:00,765:INFO:5(module)s:>>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-05-06 01:29:00,765:INFO:5(module)s:*******************]
[2025-05-06 01:29:00,765:INFO:5(module)s:>>>>>> stage Training started <<<<<<]
[2025-05-06 01:29:00,768:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-06 01:29:00,769:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-06 01:29:00,769:INFO:5(module)s:created directory at: artifacts]
[2025-05-06 01:29:00,774:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-05-06 01:29:00,775:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-05-06 01:29:00,776:INFO:5(module)s:created directory at: artifacts\training]
[2025-05-06 01:29:56,125:INFO:5(module)s:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-06 01:29:56,128:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-06 01:29:56,129:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-06 01:29:56,130:INFO:5(module)s:created directory at: artifacts]
[2025-05-06 01:29:56,131:INFO:5(module)s:created directory at: artifacts/data_ingestion]
[2025-05-06 01:29:58,510:INFO:5(module)s:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 1580:0942:139476:2F5C02:681918BD
Accept-Ranges: bytes
Date: Mon, 05 May 2025 19:59:58 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10236-MAA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1746475198.586349,VS0,VE920
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 2416e6c75102cdd3134a5a98b5c11c4a037f7808
Expires: Mon, 05 May 2025 20:04:58 GMT
Source-Age: 1

]
[2025-05-06 01:29:58,886:INFO:5(module)s:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-05-06 01:29:58,886:INFO:5(module)s:*******************]
[2025-05-06 01:29:58,886:INFO:5(module)s:>>>>>> stage Prepare base model started <<<<<<]
[2025-05-06 01:29:58,888:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-06 01:29:58,890:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-06 01:29:58,890:INFO:5(module)s:created directory at: artifacts]
[2025-05-06 01:29:58,891:INFO:5(module)s:created directory at: artifacts/prepare_base_model]
[2025-05-06 01:29:59,761:INFO:5(module)s:>>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-05-06 01:29:59,762:INFO:5(module)s:*******************]
[2025-05-06 01:29:59,762:INFO:5(module)s:>>>>>> stage Training started <<<<<<]
[2025-05-06 01:29:59,764:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-06 01:29:59,766:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-06 01:29:59,766:INFO:5(module)s:created directory at: artifacts]
[2025-05-06 01:29:59,768:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-05-06 01:29:59,769:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-05-06 01:29:59,770:INFO:5(module)s:created directory at: artifacts\training]
[2025-05-06 01:32:18,986:INFO:5(module)s:>>>>>> stage Training completed <<<<<<

x==========x]
[2025-05-06 02:06:21,303:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-06 02:06:21,306:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-06 02:06:21,307:INFO:5(module)s:created directory at: artifacts]
[2025-05-06 02:07:05,430:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-06 02:07:05,433:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-06 02:07:05,434:INFO:5(module)s:created directory at: artifacts]
[2025-05-06 02:07:35,578:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-06 02:07:35,581:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-06 02:07:35,583:INFO:5(module)s:created directory at: artifacts]
[2025-05-06 02:07:43,827:INFO:5(module)s:json file saved at:scores.json]
[2025-05-06 02:19:34,686:INFO:5(module)s:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-06 02:19:34,689:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-06 02:19:34,691:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-06 02:19:34,691:INFO:5(module)s:created directory at: artifacts]
[2025-05-06 02:19:34,693:INFO:5(module)s:created directory at: artifacts/data_ingestion]
[2025-05-06 02:19:40,575:INFO:5(module)s:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 2EE6:08A5:2B2030:7036E6:6819245F
Accept-Ranges: bytes
Date: Mon, 05 May 2025 20:49:37 GMT
Via: 1.1 varnish
X-Served-By: cache-bom4743-BOM
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1746478176.275689,VS0,VE922
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 7dacc5a0e3180bfbd7aa5f70159d23db17873f6d
Expires: Mon, 05 May 2025 20:54:37 GMT
Source-Age: 1

]
[2025-05-06 02:19:41,093:INFO:5(module)s:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-05-06 02:19:41,093:INFO:5(module)s:*******************]
[2025-05-06 02:19:41,094:INFO:5(module)s:>>>>>> stage Prepare base model started <<<<<<]
[2025-05-06 02:19:41,095:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-06 02:19:41,098:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-06 02:19:41,099:INFO:5(module)s:created directory at: artifacts]
[2025-05-06 02:19:41,100:INFO:5(module)s:created directory at: artifacts/prepare_base_model]
[2025-05-06 02:19:42,419:INFO:5(module)s:>>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-05-06 02:19:42,419:INFO:5(module)s:*******************]
[2025-05-06 02:19:42,419:INFO:5(module)s:>>>>>> stage Training started <<<<<<]
[2025-05-06 02:19:42,422:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-06 02:19:42,424:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-06 02:19:42,425:INFO:5(module)s:created directory at: artifacts]
[2025-05-06 02:19:42,427:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-05-06 02:19:42,427:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-05-06 02:19:42,429:INFO:5(module)s:created directory at: artifacts\training]
[2025-05-06 02:21:47,424:INFO:5(module)s:>>>>>> stage Training completed <<<<<<

x==========x]
[2025-05-06 02:21:47,424:INFO:5(module)s:*******************]
[2025-05-06 02:21:47,424:INFO:5(module)s:>>>>>> stage Evaluation stage started <<<<<<]
[2025-05-06 02:21:47,427:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-06 02:21:47,429:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-06 02:21:47,429:INFO:5(module)s:created directory at: artifacts]
[2025-05-06 02:21:57,969:INFO:5(module)s:json file saved at:scores.json]
[2025-05-06 02:21:57,969:INFO:5(module)s:>>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-05-06 14:48:25,273:INFO:5(module)s:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-06 14:48:25,276:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-06 14:48:25,277:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-06 14:48:25,278:INFO:5(module)s:created directory at: artifacts]
[2025-05-06 14:48:25,279:INFO:5(module)s:created directory at: artifacts/data_ingestion]
[2025-05-06 14:48:25,280:INFO:5(module)s:File already exists of size: ~ 11345 KB]
[2025-05-06 14:48:25,679:INFO:5(module)s:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-05-06 15:18:51,062:INFO:5(module)s:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-06 15:18:51,075:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-06 15:18:51,077:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-06 15:18:51,078:INFO:5(module)s:created directory at: artifacts]
[2025-05-06 15:18:51,078:INFO:5(module)s:created directory at: artifacts/data_ingestion]
[2025-05-06 15:19:22,214:INFO:5(module)s:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: D816:15DC62:69E6:C58B:6819DB09
Accept-Ranges: bytes
Date: Tue, 06 May 2025 09:48:59 GMT
Via: 1.1 varnish
X-Served-By: cache-bom4730-BOM
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1746524938.024483,VS0,VE1098
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: eea23a4ce2e315b1c98c049375d4a3b7d013ec4c
Expires: Tue, 06 May 2025 09:53:59 GMT
Source-Age: 1

]
[2025-05-06 15:19:22,618:INFO:5(module)s:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-05-06 15:22:55,325:INFO:5(module)s:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-06 15:22:55,325:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-06 15:22:55,325:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-06 15:22:55,325:INFO:5(module)s:created directory at: artifacts]
[2025-05-06 15:22:55,325:INFO:5(module)s:created directory at: artifacts/data_ingestion]
[2025-05-06 15:22:55,325:INFO:5(module)s:File already exists of size: ~ 11345 KB]
[2025-05-06 15:22:55,695:INFO:5(module)s:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-05-06 15:23:18,172:INFO:5(module)s:*******************]
[2025-05-06 15:23:18,172:INFO:5(module)s:>>>>>> stage Prepare base model started <<<<<<]
[2025-05-06 15:23:18,174:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-06 15:23:18,176:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-06 15:23:18,176:INFO:5(module)s:created directory at: artifacts]
[2025-05-06 15:23:18,177:INFO:5(module)s:created directory at: artifacts/prepare_base_model]
[2025-05-06 15:23:19,220:INFO:5(module)s:>>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-05-06 15:23:27,206:INFO:5(module)s:*******************]
[2025-05-06 15:23:27,206:INFO:5(module)s:>>>>>> stage Training started <<<<<<]
[2025-05-06 15:23:27,206:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-06 15:23:27,206:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-06 15:23:27,206:INFO:5(module)s:created directory at: artifacts]
[2025-05-06 15:23:27,206:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-05-06 15:23:27,215:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-05-06 15:23:27,215:INFO:5(module)s:created directory at: artifacts\training]
[2025-05-06 15:25:22,222:INFO:5(module)s:>>>>>> stage Training completed <<<<<<

x==========x]
[2025-05-06 15:32:07,961:INFO:5(module)s:*******************]
[2025-05-06 15:32:07,961:INFO:5(module)s:>>>>>> stage Training started <<<<<<]
[2025-05-06 15:32:07,961:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-06 15:32:07,968:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-06 15:32:07,968:INFO:5(module)s:created directory at: artifacts]
[2025-05-06 15:32:07,968:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-05-06 15:32:07,968:INFO:5(module)s:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-05-06 15:32:07,973:INFO:5(module)s:created directory at: artifacts\training]
[2025-05-06 15:34:01,206:INFO:5(module)s:>>>>>> stage Training completed <<<<<<

x==========x]
[2025-05-06 15:34:09,088:INFO:5(module)s:*******************]
[2025-05-06 15:34:09,088:INFO:5(module)s:>>>>>> stage Evaluation stage started <<<<<<]
[2025-05-06 15:34:09,091:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-06 15:34:09,093:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-06 15:34:09,094:INFO:5(module)s:created directory at: artifacts]
[2025-05-06 15:34:17,421:INFO:5(module)s:json file saved at:scores.json]
[2025-05-06 15:34:17,421:INFO:5(module)s:>>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-05-07 02:14:20,808:INFO:5(module)s:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.1.7:80]
[2025-05-07 02:14:20,809:INFO:5(module)s:[33mPress CTRL+C to quit[0m]
[2025-05-07 02:14:28,209:INFO:5(module)s:127.0.0.1 - - [07/May/2025 02:14:28] "GET / HTTP/1.1" 200 -]
[2025-05-07 02:14:58,932:ERROR:5(module)s:Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\OneDrive\Documents\Data_science 2024\CNN_classifier\CNN_Classifier\app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\monish\onedrive\documents\data_science 2024\cnn_classifier\cnn_classifier\src\cnnClassifier\pipeline\predict.py", line 15, in predict
    test_image = image.load_image(imagename,target_size = (224,224))
                 ^^^^^^^^^^^^^^^^
AttributeError: module 'keras._tf_keras.keras.preprocessing.image' has no attribute 'load_image'. Did you mean: 'load_img'?
[2025-05-07 02:14:58,939:INFO:5(module)s:127.0.0.1 - - [07/May/2025 02:14:58] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-05-07 02:15:52,263:INFO:5(module)s:127.0.0.1 - - [07/May/2025 02:15:52] "GET / HTTP/1.1" 200 -]
[2025-05-07 02:15:54,630:ERROR:5(module)s:Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\OneDrive\Documents\Data_science 2024\CNN_classifier\CNN_Classifier\app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\monish\onedrive\documents\data_science 2024\cnn_classifier\cnn_classifier\src\cnnClassifier\pipeline\predict.py", line 15, in predict
    test_image = image.load_image(imagename,target_size = (224,224))
                 ^^^^^^^^^^^^^^^^
AttributeError: module 'keras._tf_keras.keras.preprocessing.image' has no attribute 'load_image'. Did you mean: 'load_img'?
[2025-05-07 02:15:54,634:INFO:5(module)s:127.0.0.1 - - [07/May/2025 02:15:54] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-05-07 02:16:01,889:INFO:5(module)s:127.0.0.1 - - [07/May/2025 02:16:01] "GET / HTTP/1.1" 200 -]
[2025-05-07 02:16:12,747:ERROR:5(module)s:Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\OneDrive\Documents\Data_science 2024\CNN_classifier\CNN_Classifier\app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\monish\onedrive\documents\data_science 2024\cnn_classifier\cnn_classifier\src\cnnClassifier\pipeline\predict.py", line 15, in predict
    test_image = image.load_image(imagename,target_size = (224,224))
                 ^^^^^^^^^^^^^^^^
AttributeError: module 'keras._tf_keras.keras.preprocessing.image' has no attribute 'load_image'. Did you mean: 'load_img'?
[2025-05-07 02:16:12,749:INFO:5(module)s:127.0.0.1 - - [07/May/2025 02:16:12] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-05-07 02:18:48,772:INFO:5(module)s:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.1.7:80]
[2025-05-07 02:18:48,773:INFO:5(module)s:[33mPress CTRL+C to quit[0m]
[2025-05-07 02:18:52,937:INFO:5(module)s:127.0.0.1 - - [07/May/2025 02:18:52] "GET / HTTP/1.1" 200 -]
[2025-05-07 02:18:58,591:ERROR:5(module)s:Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\OneDrive\Documents\Data_science 2024\CNN_classifier\CNN_Classifier\app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\monish\onedrive\documents\data_science 2024\cnn_classifier\cnn_classifier\src\cnnClassifier\pipeline\predict.py", line 16, in predict
    model = load_model(os.path.join("artifacts","training", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\keras\src\saving\saving_api.py", line 196, in load_model
    return legacy_h5_format.load_model_from_hdf5(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\h5py\_hl\files.py", line 561, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MONISH\anaconda3\envs\myenv\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'artifacts\training\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2025-05-07 02:18:58,603:INFO:5(module)s:127.0.0.1 - - [07/May/2025 02:18:58] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-05-07 02:20:47,109:INFO:5(module)s:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.1.7:80]
[2025-05-07 02:20:47,109:INFO:5(module)s:[33mPress CTRL+C to quit[0m]
[2025-05-07 02:20:47,204:INFO:5(module)s:127.0.0.1 - - [07/May/2025 02:20:47] "GET / HTTP/1.1" 200 -]
[2025-05-07 02:20:57,543:INFO:5(module)s:127.0.0.1 - - [07/May/2025 02:20:57] "POST /predict HTTP/1.1" 200 -]
[2025-05-07 02:21:01,178:INFO:5(module)s:127.0.0.1 - - [07/May/2025 02:21:01] "POST /predict HTTP/1.1" 200 -]
[2025-05-07 02:21:14,684:INFO:5(module)s:127.0.0.1 - - [07/May/2025 02:21:14] "POST /predict HTTP/1.1" 200 -]
[2025-05-07 02:21:16,531:INFO:5(module)s:127.0.0.1 - - [07/May/2025 02:21:16] "POST /predict HTTP/1.1" 200 -]
